name: .NET Workflow

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *' 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x' 

      - name: Restaurar dependências
        run: dotnet restore

      - name: Compilar a aplicação
        run: dotnet build --configuration Release

      - name: Executar testes (script personalizado)
        run: dotnet test --no-build --verbosity normal